In [1]:
# nd_array_ 
# support GPU
# immutable

import tensorflow as tf


In [2]:
# 1 -   create tensors
 # scalar, rank 0
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
x = tf.constant(4, shape = (1,1), dtype=float)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [4]:
# vector, rank 2 
x = tf.constant([1,2,3])
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [5]:
# matrix, rank 2
x = tf.constant([[1,2,3], [4,5,3]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 3]], shape=(2, 3), dtype=int32)


In [6]:
tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 3]], shape=(2, 3), dtype=int32)


In [7]:
x = tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [8]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])
z = x + y
print(z)
z = x/y
print(z)
z = tf.tensordot([1,2],[0,1], axes=1)
print(z)


tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
tf.Tensor(2, shape=(), dtype=int32)


In [27]:
# indexing
x = tf.constant([[1,7,3,4],[1,2,8,5]])
print(x[0][2])
print(x[:,0]) # first element of each column
print(x[1, 1:3]) 
print(x[0,1])
print(x[1,:])

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([2 8], shape=(2,), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor([1 2 8 5], shape=(4,), dtype=int32)
